// Wraps the compiled Parity contract (generated by `npm run compact` into
// ./managed) into the `CompiledContract` binding that `deployContract` /
// `findDeployedContract` require. The witnesses are the same ones the Node test
// simulator uses, applied here to whichever identity the browser session is
// currently acting as.
import * as CompiledContract from "@midnight-ntwrk/compact-js/effect/CompiledContract";
import { Contract } from "../../managed/contract/index.js";
import type { WitnessContext } from "@midnight-ntwrk/compact-runtime";
import type { Ledger } from "../../managed/contract/index.js";
import type { ParityPrivateState } from "../midnight/types.js";

const w = <T>(f: (s: ParityPrivateState) => T) =>
  ({ privateState }: WitnessContext<Ledger, ParityPrivateState>): [ParityPrivateState, T] =>
    [privateState, f(privateState)];

const witnesses = {
  employerIds: w((s) => s.employerIds),
  employerSalaries: w((s) => s.employerSalaries),
  employerGroupA: w((s) => s.employerGroupA),
  employerActive: w((s) => s.employerActive),
  employeeSecretKey: w((s) => s.employeeSecretKey),
  employeeSalary: w((s) => s.employeeSalary),
  employeeIsGroupA: w((s) => s.employeeIsGroupA),
  merkleSiblings: w((s) => s.merkleSiblings),
  merklePathIndices: w((s) => s.merklePathIndices),
  employerClaimedRecordHash: w((s) => s.employerClaimedRecordHash),
};

// The "compiled assets path" below is a required tag for the binding; the ZK
// artifact bytes are fetched at runtime over HTTP by the FetchZkConfigProvider
// configured in providers.ts.
export const parityCompiledContract = CompiledContract.make<Contract<ParityPrivateState>>(
  "Parity",
  Contract,
).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets("contract"),
);

// The three provable (on-chain) circuits exposed by the compiled contract.
export type ParityCircuitId = "commitPayroll" | "confirmRecord" | "disputeRecord";
